#!/bin/sh
# we cat /etc/passwd like normal
# we do everything with awk this time
# -F value is hte delimiter that we use
# !/#/ ignores comment lines that start with #
# add some fancy coloring to the output for ease of reading
# then we print fields 1, 3 and 7 for Login, UID, and path of command
# field 6 would be for the home directory
# then we make the output bit more readable with column -t so colums align
echo "Want to display only login, UID and Path of each entry of the /etc/passwd file?"
while read -p "y/n? " answer
do
	if [ $answer == 'y' ]; 
		then
			cat /etc/passwd | awk -F ':' '!/#/ {print "\033[32m" $1, "\033[36m" $3,"\033[33m" $7}' | column -t
			break
	elif [ $answer == 'n' ]; 
		then
			echo "Too bad, all this for NOTHING!"
			break
	else	
		echo "Please write 'y' for yes, and 'n' for no and try again."
		continue
	fi
done
